version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/node-ts-monorepo'
    schedule:
      interval: 'daily'

  - package-ecosystem: 'npm'
    directory: '/node-ts-monorepo/scripts/create-package'
    schedule:
      interval: 'daily'

  - package-ecosystem: 'npm'
    directory: '/node-ts-monorepo/scripts/script-utils'
    schedule:
      interval: 'daily'

  - package-ecosystem: 'npm'
    directory: '/node-ts-package'
    schedule:
      interval: 'daily'
