version: 2
updates:
  # Updates for the node-ts-monorepo template
  - package-ecosystem: 'npm'
    directory: '/node-ts-monorepo'
    schedule:
      interval: 'weekly'
    groups:
      node-ts-monorepo-dev-dependencies:
        dependency-type: 'development'

  # Updates for the node-ts-package template
  - package-ecosystem: 'npm'
    directory: '/node-ts-package'
    schedule:
      interval: 'weekly'
    groups:
      node-ts-package-dev-dependencies:
        dependency-type: 'development'
